name: Deploy to S3

on:
  push:
    branches:
      - main   # change if your repo uses "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1   

          - name: Sync files to S3
        run: |
          aws s3 sync . s3://car-website16 --delete --acl public-read

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://your-bucket-name --delete --acl public-read
